### ISSUE TITLE
Can't install frida with npm (seems related to node v10)

### ISSUE THREAD

**Issue by LouisonGitzinger** [frida/frida#487]
Hi there, 
First, thanks a lot for everything linked to frida, it is very useful !

I tried to install through npm like it is specified in the readme.md : 
```npm install frida```
Here is the error I have : 

```
> npm install frida

> frida@10.8.0 install /Users/lgitzing/Development/work/frida_masterplace/node_modules/frida
> prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=10.0.0 runtime=node arch=x64 platform=darwin)
  CXX(target) Release/obj.target/frida_binding/src/addon.o
In file included from ../src/addon.cc:1:
In file included from ../src/application.h:4:
In file included from ../src/glib_object.h:4:
In file included from ../src/runtime.h:4:
../src/glib_context.h:4:10: fatal error: 'frida-core.h' file not found
#include <frida-core.h>
         ^~~~~~~~~~~~~~
1 error generated.
make: *** [Release/obj.target/frida_binding/src/addon.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:225:12)
gyp ERR! System Darwin 17.5.0
gyp ERR! command "/usr/local/Cellar/node/9.10.1/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/lgitzing/Development/work/frida_masterplace/node_modules/frida
gyp ERR! node -v v10.0.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN frida_masterplace@1.0.0 No description
npm WARN frida_masterplace@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! frida@10.8.0 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the frida@10.8.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/lgitzing/.npm/_logs/2018-04-30T15_35_33_855Z-debug.log
```

I'm working on macOS 10.13.4

I actually need to install it to work with frida-trace : https://github.com/nowsecure/frida-trace.
I already have the binary installed thanks to the ```pip``` command.

Thank you in advance for your help

**Comment by WarrenHood** [comment]
$ npm install frida
npm WARN lifecycle The node binary used for scripts is /data/data/com.termux/files/home/.nvm/versions/node/v10.0.0/bin/node but npm is using /data/data/com.termux/files/usr/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> frida@10.8.1 install /data/data/com.termux/files/home/node_modules/frida
> prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=8.11.1 runtime=node arch=arm platform=android)
gyp: Undefined variable frida_host in binding.gyp while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/data/data/com.termux/files/home/.nvm/versions/node/v10.0.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 3.4.112-kali
gyp ERR! command "/data/data/com.termux/files/usr/bin/node" "/data/data/com.termux/files/home/.nvm/versions/node/v10.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /data/data/com.termux/files/home/node_modules/frida
gyp ERR! node -v v8.11.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open '/data/data/com.termux/files/home/package.json'
npm WARN home No description
npm WARN home No repository field.
npm WARN home No README data
npm WARN home No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"android","arch":"arm"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! frida@10.8.1 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the frida@10.8.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /data/data/com.termux/files/home/.npm/_logs/2018-05-01T16_03_52_022Z-debug.log

**Comment by LouisonGitzinger** [comment]
Hi there, the problem seems to be solved with frida 10.8.2 today : 
```
~
❯ npm install -g frida

> frida@10.8.2 install /usr/local/lib/node_modules/frida
> prebuild-install || node-gyp rebuild

+ frida@10.8.2
added 69 packages in 2.197s
```

Thanks !

**Comment by pharazone** [comment]
MacOS 10.14.4    the same problem

**Comment by 4val0v** [comment]
And I have the same problem

MacOS: 10.15.4
```
$ node -v
v14.1.0
```
```
$ npm -v
6.14.4
```
