### ISSUE TITLE
Issue where frida-ps -U hangs with no output

### ISSUE THREAD

**Issue by jshchnz** [frida/frida#1784]
I have a jailbroken iPhone X on iOS 14.6. I'm able to verify that I can SSH into the device with root access and I can see the device listed using `frida-ls-devices` however, when I try to use `frida-ps -U` or any frida command it just hangs. No log output is given or any indication of what is going on, any ideas?

**Comment by jshchnz** [comment]
I've now tried updating to Frida 15 and I'm getting a different error:

`PID  Name
----  --------------------------------------------------------
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/site-packages/frida_tools/application.py", line 639, in _run
    work()
  File "/usr/local/lib/python3.9/site-packages/frida_tools/application.py", line 334, in _try_start
    self._start()
  File "/usr/local/lib/python3.9/site-packages/frida_tools/ps.py", line 34, in _start
    self._list_processes()
  File "/usr/local/lib/python3.9/site-packages/frida_tools/ps.py", line 52, in _list_processes
    for process in sorted(processes, key=cmp_to_key(compare_processes)):
  File "/usr/local/lib/python3.9/site-packages/frida_tools/ps.py", line 147, in __lt__
    return mycmp(self.obj, other.obj) < 0
  File "/usr/local/lib/python3.9/site-packages/frida_tools/ps.py", line 126, in compare_processes
    a_has_icon = a.get_small_icon() is not None
AttributeError: '_frida.Process' object has no attribute 'get_small_icon'`

**Comment by jshchnz** [comment]
And now unfortunately my previously working jailbroken iPhone 7 on 13.6 has now stopped working.

```
➜  ~ frida-ps -U
Failed to enumerate processes: this feature requires an iOS Developer Disk Image to be mounted; run Xcode briefly or use ideviceimagemounter to mount one manually
```

**Comment by oleavr** [comment]
> I've now tried updating to Frida 15 and I'm getting a different error:

You need to update frida-tools as well.

> And now unfortunately my previously working jailbroken iPhone 7 on 13.6 has now stopped working.

Switch to Frida 15. You need the latest for the latest jailbreak support – simply installing package updates (such as Substrate) is enough to require the latest Frida.

**Comment by arydob** [comment]
I had the same issue
Do you same version of both client and server?

**Comment by jshchnz** [comment]
So just to update everyone. I did get Frida working on iOS 14.6 on an iPhone X. It required updating to Frida 15 and updating the accompanying frida-tools. However, since I've upgraded it now seems to have stopped working with my iPhone 7 on iOS 13.
